
export const ADD_NEW_SYMPTOMS = "ADD_NEW_SYMPTOMS";
export const ADD_NEW_SYMPTOMS_SUCCESS = "ADD_NEW_SYMPTOMS_SUCCESS";


export const GET_SYMPTOMS_LIST = "GET_SYMPTOMS_LIST";
export const GET_SYMPTOMS_LIST_SUCCESS = "GET_SYMPTOMS_LIST_SUCCESS";

export const UPDATE_SYMPTOMS_DATA = "UPDATE_SYMPTOMS_DATA";
export const UPDATE_SYMPTOMS_DATA_SUCCESS = "UPDATE_SYMPTOMS_DATA_SUCCESS";