

export const GET_PATIENTS_LIST = "GET_PATIENTS_LIST";
export const GET_PATIENTS_LIST_SUCCESS = "GET_PATIENTS_LIST_SUCCESS";

export const GET_PATIENTS_SINGLE_VIEW = "GET_PATIENTS_SINGLE_VIEW";
export const GET_PATIENTS_SINGLE_VIEW_SUCCESS = "GET_PATIENTS_SINGLE_VIEW_SUCCESS";
export const GET_PATIENTS_SINGLE_VIEW_FAILED = "GET_PATIENTS_SINGLE_VIEW_FAILED";

export const ADD_PATIENT_DATA = "ADD_PATIENT_DATA";
export const ADD_PATIENT_DATA_SUCCESS = "ADD_PATIENT_DATA_SUCCESS";

export const UPDATE_PATIENT_DATA = "UPDATE_PATIENT_DATA";
export const UPDATE_PATIENT_DATA_SUCCESS = "UPDATE_PATIENT_DATA_SUCCESS";

export const DELETE_PATIENT_DATA = "DELETE_PATIENT_DATA";
export const DELETE_PATIENT_DATA_SUCCESS = "DELETE_PATIENT_DATA_SUCCESS";


export const GET_MY_PRESCRIPTIONS_LIST = "GET_MY_PRESCRIPTIONS_LIST";
export const GET_MY_PRESCRIPTIONS_LIST_SUCCESS = "GET_MY_PRESCRIPTIONS_LIST_SUCCESS";


export const DOWNLOAD_PRESCRIPTION = "DOWNLOAD_PRESCRIPTION";
export const DOWNLOAD_PRESCRIPTION_SUCCESS = "DOWNLOAD_PRESCRIPTION_SUCCESS";


export const GET_PATIENTS_SYMPTOMS_LIST = "GET_PATIENTS_SYMPTOMS_LIST";
export const GET_PATIENTS_SYMPTOMS_LIST_SUCCESS = "GET_PATIENTS_SYMPTOMS_LIST_SUCCESS";

export const DELETE_PATIENTS_SYMPTOMS = "DELETE_PATIENTS_SYMPTOMS";
export const DELETE_PATIENTS_SYMPTOMS_SUCCESS = "DELETE_PATIENTS_SYMPTOMS_SUCCESS";

export const ADD_PAYPAL_PAYMENT = "ADD_PAYPAL_PAYMENT";