

export const GET_DOCTORS_LIST = "GET_DOCTORS_LIST";
export const GET_DOCTORS_LIST_SUCCESS = "GET_DOCTORS_LIST_SUCCESS";


export const ADD_PRESCRIPTIONS = "ADD_PRESCRIPTIONS";
export const ADD_PRESCRIPTIONS_SUCCESS = "ADD_PRESCRIPTIONS_SUCCESS";

export const GET_PAYPAL_TRANSACTIONS = "GET_PAYPAL_TRANSACTIONS";
export const GET_PAYPAL_TRANSACTIONS_SUCCESS = "GET_PAYPAL_TRANSACTIONS_SUCCESS";